package com.gempukku.stccg.effects.utils;

public enum EffectType {

    BEFORE_EXERT, BEFORE_DISCARD_FROM_PLAY,
    BEFORE_ADD_TWILIGHT, BEFORE_KILLED, BEFORE_HEALED,
    BEFORE_SKIRMISH_RESOLVED,
    BEFORE_THREAT_WOUNDS,
    BEFORE_DRAW_CARD,
    BEFORE_MOVE_FROM, BEFORE_MOVE, BEFORE_MOVE_TO,
    ACTIVATE_TRIBBLE_POWER

}
