package com.gempukku.stccg.actions;

public enum ActionResultType {
    ACTIVATE_TRIBBLE_POWER,
    ADD_CARDS_TO_PRESEED_STACK,
    BEAM_CARDS,
    CHANGE_AFFILIATION,
    DISCARD,
    DRAW_CARD,
    END_OF_TURN,
    JUST_PLAYED,
    KILL,
    NULLIFY,
    PLAYER_WENT_OUT,
    RANDOM_SELECTION_INITIATED,
    REMOVE_CARD_FROM_GAME,
    SOLVE_MISSION,
    START_OF_MISSION_ATTEMPT,
    START_OF_TURN,
    WALK_CARDS
}