package com.gempukku.stccg.actions;

public enum ActionResultType {
    ACTIVATE_TRIBBLE_POWER,
    DRAW_CARD,
    END_OF_TURN,
    FOR_EACH_DISCARDED_FROM_HAND,
    JUST_DISCARDED_FROM_PLAY,
    JUST_PLAYED,
    KILL_CARD,
    PLAYER_WENT_OUT,
    RANDOM_SELECTION_INITIATED,
    SOLVE_MISSION,
    START_OF_MISSION_ATTEMPT,
    START_OF_PHASE,
    ADD_CARDS_TO_PRESEED_STACK, START_OF_TURN
}