package com.gempukku.stccg.common.filterable;

@SuppressWarnings({"SpellCheckingInspection", "unused"})
public enum ShipClass implements Filterable {

    AMBASSADOR, ASSAULT,
    BORG_ASSIMILATOR,
    CLASS_D_12_SCOUT_VESSEL,
    D_DERIDEX, D_KORA, EXCELSIOR, GALAXY, GALOR, INTERCEPTOR, INTREPID, K_VORT, KELDON, MERCHANT,
    NA_FAR, NEBULA, OBERTH, RUNABOUT, SCIENCE, SCOUT, SOVEREIGN, UNKNOWN, VOR_CHA, WAMBUNDU, ZIBALIAN,
    MERCHANT_FREIGHTER, SHUTTLECRAFT, TYPE_VI_SHUTTLECRAFT
}