package com.gempukku.stccg.modifiers;

public enum ModifierEffect {
    STRENGTH_MODIFIER, CUNNING_MODIFIER, STRENGTH_BONUS_SOURCE_MODIFIER,
    GAIN_ICON_MODIFIER,
    STRENGTH_BONUS_TARGET_MODIFIER,
    ACTION_MODIFIER, DISCARD_FROM_PLAY_MODIFIER, DISCARD_NOT_FROM_PLAY,
    LOOK_OR_REVEAL_MODIFIER, TARGET_MODIFIER, RETURN_TO_HAND_MODIFIER,
    EXTRA_ACTION_MODIFIER, EXTRA_COST_MODIFIER,
    TEXT_MODIFIER,
    SPECIAL_FLAG_MODIFIER,
    PLAY_OUT_OF_SEQUENCE,
    ALL_ATTRIBUTE_MODIFIER, INTEGRITY_MODIFIER, GAIN_SKILL_MODIFIER, IDIC_BONUS,
    AU_CARDS_ENTER_PLAY, SOLVE_MISSION_MODIFIER
}