package com.gempukku.stccg.modifiers;

public enum ModifierEffect {
    STRENGTH_MODIFIER, CUNNING_MODIFIER, STRENGTH_BONUS_SOURCE_MODIFIER,
    GAIN_ICON_MODIFIER,
    STRENGTH_BONUS_TARGET_MODIFIER,
    TWILIGHT_COST_MODIFIER,
    PRESENCE_MODIFIER, MOVE_LIMIT_MODIFIER, ACTION_MODIFIER, DISCARD_FROM_PLAY_MODIFIER, DISCARD_NOT_FROM_PLAY,
    LOOK_OR_REVEAL_MODIFIER, SPOT_MODIFIER, TARGET_MODIFIER, RETURN_TO_HAND_MODIFIER, TRANSFER_MODIFIER,
    LIBERATION_MODIFIER, EXTRA_ACTION_MODIFIER, EXTRA_COST_MODIFIER,
    INITIATIVE_MODIFIER, TEXT_MODIFIER,

    SPECIAL_FLAG_MODIFIER, PLAY_SITE_MODIFIER,

    ADDITIONAL_CARD_TYPE,

    REMOVE_KEYWORD_MODIFIER, GIVE_KEYWORD_MODIFIER, CANCEL_KEYWORD_BONUS_TARGET_MODIFIER, LOSE_ALL_KEYWORDS_MODIFIER,

    POTENTIAL_DISCOUNT_MODIFIER,

    PLAY_OUT_OF_SEQUENCE,
    ALL_ATTRIBUTE_MODIFIER, INTEGRITY_MODIFIER, IDIC_BONUS
}
