package com.gempukku.stccg.modifiers;

public enum ModifierEffect {
    ATTRIBUTE_MODIFIER,
    WEAPONS_DISABLED_MODIFIER,
    GAIN_ICON_MODIFIER,
    ACTION_MODIFIER,
    DISCARD_NOT_FROM_PLAY,
    EXTRA_COST_MODIFIER,
    TEXT_MODIFIER,
    SPECIAL_FLAG_MODIFIER,
    PLAY_OUT_OF_SEQUENCE,
    GAIN_SKILL_MODIFIER,
    AU_CARDS_ENTER_PLAY, ADD_ICON_TO_MISSION, SOLVE_MISSION_MODIFIER,
    COMPATIBILITY_MODIFIER, MISSION_ATTEMPT_MODIFIER
}